rapidsai/cuxfilter

.github/workflows/new-issues-to-triage-projects.yml

New GitHub Action to move new issues to their appropriate triage projects.
No need for CI as this is not a code change. Review is needed to make sure that correct projects are linked.
---
@exactlyallan FYI you did not have an `Other Issues` project so that has been created to match the other RAPIDS repos. Also `enhancement` label has been changed to `feature request` to match other repos.
I also copied the standard repo labels over so you have them.

ENH Add GH Action moving new issues to triage projects [skip-ci]

---

ci/release/update-version.sh
docs/source/conf.py

This is needed so we can have the version number in the docs output and keep it updated between releases

Fix show current version in docs [skip-ci]

---

CHANGELOG.md
ci/local/README.md
ci/local/build.sh

This script is designed for developer and contributor use. This tool mimics the actions of gpuCI on your local machine. This allows you to test and even debug your code inside a gpuCI base container before pushing your code as a GitHub commit. The script can be helpful in locally triaging and debugging RAPIDS continuous integration failures.

[REVIEW] Local gpuCI build script

---

CHANGELOG.md
python/cuxfilter/layouts/layouts.py
python/cuxfilter/tests/layouts/test_layouts.py

Hi @AjayThorve I've tried to split up and arrange the commits in a fairly atomic way, but the new `layouts` module is down to ~300 lines so it might be useful to just refer to the entire new file as well. I tested manually with the available notebooks and with the existing unit tests (more about tests below)
I factored the detection of widgets out into a function `is_widget`. My own preferences here are aggressive. It's not an exaggeration to say that once a predicate has an "and" or "or" I'm about ready to pull it into its own function. 
Almost always a win to use `enumerate` over manually fiddling with counters
I know the inclination here is probably towards loop fusion :) But in this case there are only ever single digit numbers of things to loop over, so the logic can be more clearly …

[WIP] Layouts Refactor

---

CHANGELOG.md
ci/gpu/build.sh

Install dependencies via `rapids-build-env` and `rapids-notebook-env` (which are pre-installed in the containers).
This brings the repo in line with https://docs.rapids.ai/maintainers/depmgmt/
Depends on https://github.com/rapidsai/integration/pull/49

Install dependencies via meta packages

---

ci/checks/changelog.sh
ci/cpu/upload_anaconda.sh

This PR removes unecessary references to master or updates references to the new main branch in CI scripts and other OPS-owned files.

[REVIEW] Update CI scripts to remove references to master [skip ci] 

---

ci/checks/changelog.sh
ci/cpu/upload_anaconda.sh

Auto-merge triggered by push to `branch-0.15` that creates a PR to keep `branch-0.16` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.15 to branch-0.16 [skip ci]

---

CHANGELOG.md
ci/docs/build.sh

This PR removes the conda installs from the CI doc build script since they are now all listed in the `rapids-doc-env` package in the integration repo ([src](https://github.com/rapidsai/integration/blob/branch-0.16/conda/recipes/rapids-doc-env/meta.yaml)).
Depends on https://github.com/rapidsai/integration/pull/129

Remove conda installs from doc build script [skip-ci]

---

CHANGELOG.md
ci/gpu/build.sh
conda/environments/cuxfilter_dev_cuda10.0.yml
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml
python/cuxfilter/charts/core/non_aggregate/core_graph.py
python/cuxfilter/charts/core/non_aggregate/core_non_aggregate.py
python/cuxfilter/charts/core/non_aggregate/core_stacked_line.py
python/cuxfilter/charts/datashader/plots.py
python/cuxfilter/tests/charts/core/test_core_graph.py
python/cuxfilter/tests/charts/core/test_core_non_aggregate.py
python/cuxfilter/tests/charts/core/test_core_stacked_line.py

cc @AjayThorve 
I reworked my original approach to this. At first, I had modified `get_selection_geometry_callback` to be `get_selection_geometry_callbackS` (plural) and had it return a list of callbacks to downstream consumers. This preserves the flexibility of those intermediate `temp_callback` wrappers. However, this broke quite a bit in testing and elsewhere and I was not quite confident in some of the chain of changes I had to start making. 
The current PR pushes the event itself upstream and to the `selection_callback` directly (and eliminating the intermediate `temp_callback`  functions). Then the `selection_callback` does the switching between rect and lasso events. This significantly limits the scope of changes, at the cost of some flexibility in principle. However I note that …

add lasso selection support

---

conda/recipes/cuxfilter/meta.yaml

This PR is related to https://github.com/rapidsai/integration/pull/213.
Lately we've been seeing a lot of `conda` solve issues with NodeJS version 15 (see screenshots below). The solve problems add an extra ~20 minutes to CI jobs. This PR pins the Node version so that it only uses 12-14 (for reference, [14 is the current LTS](https://nodejs.org/en/)). Hopefully this helps with the `conda` conflicts.

Pin Node version

---

conda/recipes/cuxfilter/meta.yaml

Auto-merge triggered by push to `branch-0.18` that creates a PR to keep `branch-0.19` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.18 to branch-0.19 [skip ci]

---

CHANGELOG.md
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml

Forward-merge triggered by push to `branch-0.19` that creates a PR to keep `branch-0.20` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-0.19 to branch-0.20 [skip ci]

---

docs/source/installation.rst

Remove `defaults` channel from conda build

ENH Remove defaults channel from conda build

---

conda/recipes/cuxfilter/meta.yaml

This PR updates the environment variable thats used to determine the `cuda_version` varaible in our conda recipes.
The `CUDA` environment variable is explicitly set by the Ops team in our Jenkins jobs, whereas `CUDA_VERSION` comes from the `nvidia/cuda` Docker images that we base our images from.

Update environment variable used to determine `cuda_version`

---

CHANGELOG.md
conda/recipes/cuxfilter/meta.yaml

Forward-merge triggered by push to `branch-21.06` that creates a PR to keep `branch-21.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.06 to branch-21.08 [skip ci]

---

ci/cpu/build.sh
ci/docs/build.sh
ci/gpu/build.sh
ci/gpu/test-notebooks.sh
ci/local/build.sh
ci/utils/nbtest.sh

This PR adds support for spaces in workspace

support space in workspace

---

conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml

This PR updates the `geopandas` version spec to match a recent version change in the integration repo (https://github.com/rapidsai/integration/pull/271).

Update `geopandas` version spec

---

python/cuxfilter/charts/core/aggregate/core_aggregate.py
python/cuxfilter/charts/core/core_widget.py
python/cuxfilter/dashboard.py
python/cuxfilter/layouts/custom_react_template.py
python/cuxfilter/themes/assets/rapids.css
python/cuxfilter/themes/rapids.py

Follow up PR to #303, fixes theme related bugs, which were introduced in the previous PR, while updating panel and bokeh version support. 
This PR also fixes(handles), a weird issue where the bokeh x-axis data in CDS is converted from datetime to float during runtime, which caused a bunch of issues in the computing queries.
Will have to investigate further and try and fix this issue in the base libraries instead of cuxfilter though, more work to follow regarding that.

Fix/follow up to #303

---

python/cuxfilter/assets/screengrab.py

This PR is a continuation of #307. It adds a `try`/`except` block so that `cuxfilter` can be imported without any issues if the `pyppeteer` module is missing.

Update `pyppeteer` import

---

README.md
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml
python/cuxfilter/assets/screengrab.py

Forward-merge triggered by push to `branch-21.10` that creates a PR to keep `branch-21.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.10 to branch-21.12 [skip gpuci]

---

README.md
notebooks/README.md

WIP PR to add documentation for the latest changes introduced in #324 and support for google colab and aws studio lab.
Also closes #260 by adding a note to dataset info in the readme about corrupted data

[WIP] Documentation & Notebook updates

---

python/cuxfilter/dashboard.py

Quick fix PR to fix the `_reinit_all_charts` function, which was no longer working due to the recent refactors

fix reinit function

---

ci/gpu/build.sh
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/environments/cuxfilter_dev_cuda11.2.yml
conda/environments/cuxfilter_dev_cuda11.4.yml
conda/environments/cuxfilter_dev_cuda11.5.yml
conda/recipes/cuxfilter/meta.yaml

This PR updates the `bokeh` version specification to be compatible with the specification that's used by `dask=2022.03.0` ([src](https://github.com/dask/dask/blob/2022.03.0/setup.py#L20)).

Update `bokeh` version

---

conda/environments/cuxfilter_dev_cuda11.0.yml
conda/environments/cuxfilter_dev_cuda11.2.yml
conda/environments/cuxfilter_dev_cuda11.4.yml
conda/environments/cuxfilter_dev_cuda11.5.yml
conda/recipes/cuxfilter/meta.yaml

update panel version

---

conda/recipes/cuxfilter/conda_build_config.yaml
conda/recipes/cuxfilter/meta.yaml

This PR enables the usage of conda compilers to build conda packages. This is required to use `mambabuild`

Use conda compilers

---

conda/recipes/cuxfilter/conda_build_config.yaml
conda/recipes/cuxfilter/meta.yaml

Forward-merge triggered by push to `branch-22.06` that creates a PR to keep `branch-22.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.06 to branch-22.08 [skip gpuci]

---

ci/gpu/build.sh
conda/recipes/cuxfilter/meta.yaml

The current `nodejs` version specifier is outdated and is causing issues related to https://github.com/rapidsai/cuxfilter/issues/384. This PR updates the specifier to uncap the maximum version and set a new minimum.

Update `nodejs` version specifier

---

conda/recipes/cuxfilter/meta.yaml

Forward-merge triggered by push to `branch-22.08` that creates a PR to keep `branch-22.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.08 to branch-22.10 [skip gpuci]

---

conda/environments/cuxfilter_dev_cuda11.0.yml
conda/environments/cuxfilter_dev_cuda11.2.yml
conda/environments/cuxfilter_dev_cuda11.4.yml
conda/environments/cuxfilter_dev_cuda11.5.yml
conda/recipes/cuxfilter/meta.yaml

Similarly to https://github.com/rapidsai/cuspatial/pull/585, this PR updates the `geopandas` version specifier to ensure compatibility with the rest of RAPIDS.

Update `geopandas` version specificer

---

conda/environments/cuxfilter_dev_cuda11.0.yml
conda/environments/cuxfilter_dev_cuda11.2.yml
conda/environments/cuxfilter_dev_cuda11.4.yml
conda/environments/cuxfilter_dev_cuda11.5.yml
conda/recipes/cuxfilter/meta.yaml

This PR updates the `pyproj` version specifier to be compatible with a newer version of `gdal` that will be used in `cuspatial`. `gdal` needs to be bumped to address a CVE.

Update `pyproj` version specifier

---

python/cuxfilter/tests/charts/datashader/test_graph_assets.py

When upgrading to dask 22.9.0, this test was failing as a result of a dask_dataframe compute() call resulting in a cuDF dataframe with incorrect indices (keeps partitioned indices after `map_partitions` call). 
This does not affect the behavior of graph charts in cuxfilter, so a trivial fix to the test, which compares against a result dataframe with sequential indices, is enough to resolve the issue. 
cc @galipremsagar

fix test failing on non-matching indices for newer dask version

---

conda/environments/cuxfilter_dev_cuda11.0.yml
conda/environments/cuxfilter_dev_cuda11.2.yml
conda/environments/cuxfilter_dev_cuda11.4.yml
conda/environments/cuxfilter_dev_cuda11.5.yml
conda/recipes/cuxfilter/meta.yaml

This PR allows cupy 11.
xref: https://github.com/rapidsai/integration/pull/528

Allow cupy 11

---

.pre-commit-config.yaml
ci/checks/style.sh
pyproject.toml
python/.flake8
python/setup.cfg

Updates style checks to use `pre-commit`. This was suggested in #416 and helps prepare the repository for the migration to GitHub Actions.

Update style checks to use pre-commit.

---

CHANGELOG.md
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/environments/cuxfilter_dev_cuda11.2.yml
conda/environments/cuxfilter_dev_cuda11.4.yml
conda/environments/cuxfilter_dev_cuda11.5.yml
conda/recipes/cuxfilter/meta.yaml

Forward-merge triggered by push to `branch-22.12` that creates a PR to keep `branch-23.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.12 to branch-23.02 [skip gpuci]

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
CONTRIBUTING.md
README.md
ci/test_notebooks.sh
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/recipes/cuxfilter/meta.yaml
dependencies.yaml
docs/source/installation.rst
notebooks/README.md
python/setup.py

This PR updates `cuxfilter` to build against branch [cuda-118](https://github.com/rapidsai/shared-action-workflows/compare/cuda-118) of the `shared-action-workflow` repository.
That branch contains updates for CUDA 11.8 and Python 3.10 packages.
It also includes some minor file renames.
Depends on
- https://github.com/rapidsai/cudf/pull/12457
- https://github.com/rapidsai/cuspatial/pull/865

Build CUDA 11.8 and Python 3.10 Packages

---

ci/test_notebooks.sh

The `graphs.ipynb` notebook was disabled in #426 due to some upstream issues with `cugraph`.
This PR reverts that change to re-enable the notebook.

Re-enable `graphs.ipynb` notebook in CI

---

conda/recipes/cuxfilter/meta.yaml

This PR moves the date string from the version to the build string for conda recipes in this repository.
This is necessary to ensure that the conda packages resulting from PR builds can be installed in the same environment as nightly conda packages, which is useful for testing purposes.
Additionally, this prevents a bug from occurring where the Python builds fail because the date string it computes is different than the one computed by the C++ build, therefore causing the Python build to search for a C++ build artifact that doesn't exist.
xref: https://github.com/rapidsai/rmm/pull/1195

Move date to build string in `conda` recipe

---

ci/test_notebooks.sh
ci/test_python.sh

This PR adds a less verbose trap method, for error handling to help ensure that we capture all potential error codes in our test scripts, and works as follows:
- setting an environment variable, EXITCODE, with a default value of 0
- setting a trap statement triggered by ERR signals which will set EXITCODE=1 when any commands return a non-zero exit code
cc @ajschmidt8

Reduce error handling verbosity in CI tests scripts

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml

This PR is updating the runner labels to use ARC V2 self-hosted runners for GPU jobs. This is needed to resolve the auto-scalling issues.

Use ARC V2 self-hosted runners for GPU jobs

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml
.github/workflows/test.yaml
conda/environments/all_cuda-118_arch-x86_64.yaml
dependencies.yaml
pyproject.toml
python/setup.py

This PR drops Python 3.8 in favor of 3.9.

Dropping Python 3.8

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml
.github/workflows/test.yaml

This PR reverts the shared-action-workflows branch pin that was used to drop Python 3.8 to branch-23.06

Revert shared-action-workflows pin

---

conda/recipes/cuxfilter/meta.yaml

Updating `cupy` spec to match the rest of RAPIDS

Update cupy to >=12

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/recipes/cuxfilter/meta.yaml
dependencies.yaml
python/cuxfilter/tests/assets/test_gpu_histogram.py
python/cuxfilter/tests/charts/core/test_core_graph.py
python/cuxfilter/tests/charts/utils.py

This PR:
- fixes a couple of tests which were failing due to recent changes, leading to aggregate results being unsorted
- resolves docs build failures, which were caused by datashader rendering issues with latest numpy(1.24.3), fixed by adding a pin for numpy (<1.24, similar to the version pins in cugraph). @ajschmidt8, could you check if adding this version pin is fine?

fix tests failing due to unsorted results

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/recipes/cuxfilter/meta.yaml
dependencies.yaml

Align with the rest of RAPIDS on these requirements. Also needed for CUDA 12 support.

Require Numba 0.57.0+ & NumPy 1.21.0+

---

notebooks/10_minutes_to_cuxfilter.ipynb

Follow up from #500 where a notebook was moved but the symlink in `notebooks` was not updated.
Related: #419

Fix broken symlink

---

.github/workflows/test.yaml

This PR fixes the nightly wheel testing workflow. It looks like this was copied straight from `pr.yaml` rather than adapted for nightly testing.
```
Invalid workflow file: .github/workflows/test.yaml#L26
The workflow is not valid. .github/workflows/test.yaml (Line: 26, Col: 12): Job 'wheel-tests' depends on unknown job 'wheel-build'.
```
https://github.com/rapidsai/cuxfilter/actions/runs/5653917680

Fix nightly wheel testing workflow.

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
.pre-commit-config.yaml
dependencies.yaml

This PR builds conda packages using CUDA 12 on ARM.
Closes #538.

Build CUDA 12.0 ARM conda packages.

---

EXTERNAL_TESTS.md
ci/release/update-version.sh
ci/test_external.sh
ci/utils/external_dependencies.yaml

This PR resolves the external tests still failing: https://github.com/rapidsai/cuxfilter/actions/runs/6485671242/job/17612261430.
Basically separately installing direct dependencies and then installing indirect dependencies from dependencies.yaml was downgrading rapids versions to 23.08 separately. This PR updates the dependencies to be in a single place (external_dependencies.yaml), while also adding it to `ci/release/update-version.sh`
There were a couple of dask.array tests in datashader which were failing when using `pytest`  with `--numprocesses` flag, which is resolved here by separately running that test without the flag.
cc @exactlyallan

updates to external tests

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml
.github/workflows/test.yaml
ci/release/update-version.sh

Update `shared-action-workflows` references to `shared-actions` following the work to rename the `rapidsai/shared-action-workflows` to `rapidsai/shared-workflows`.

Update `shared-action-workflows` references

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-120_arch-x86_64.yaml
dependencies.yaml
python/cuxfilter/assets/geojson_mapper.py
python/cuxfilter/charts/bokeh/plots/bar.py
python/cuxfilter/charts/bokeh/plots/histogram.py
python/cuxfilter/charts/core/aggregate/core_aggregate.py
python/cuxfilter/charts/core/non_aggregate/utils.py
python/cuxfilter/charts/deckgl/bindings/panel_deck.py
python/cuxfilter/charts/panel_widgets/plots.py
python/cuxfilter/dashboard.py
python/cuxfilter/tests/charts/deckgl/test_deckgl.py

[Ready for Review] Pandas 2.0 compatibility

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml
.github/workflows/test.yaml

Follow-up to #563
For all GitHub Actions configs, replaces uses of the `test-cuda-12.2` branch on `shared-workflows`
with `branch-24.04`, now that https://github.com/rapidsai/shared-workflows/pull/166 has been merged.
This is part of ongoing work to build and test packages against CUDA 12.2 across all of RAPIDS.
For more details see:
* https://github.com/rapidsai/build-planning/issues/7
*(created with `rapids-reviser`)*

target branch-24.04 for GitHub Actions workflows

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
README.md
ci/utils/external_dependencies.yaml
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-122_arch-x86_64.yaml
dependencies.yaml
notebooks/README.md
python/pyproject.toml

Contributes to https://github.com/rapidsai/build-planning/issues/3
This PR adds support for Python 3.11.
This is part of ongoing work to add Python 3.11 support across RAPIDS.
The Python 3.11 CI workflows introduced in https://github.com/rapidsai/shared-workflows/pull/176 are *optional*... they are not yet required to run successfully for PRs to be merged.
This PR can be merged once all jobs are running successfully (including the non-required jobs for Python 3.11). The CI logs should be verified that the jobs are building and testing with Python 3.11.
See https://github.com/rapidsai/shared-workflows/pull/176 for more details.

Add support for Python 3.11

---

ci/test_external.sh
ci/test_python.sh

This PR uses the `worksteal` algorithm to accelerate parallel pytests. See https://github.com/rapidsai/cudf/pull/15207.

Switch `pytest-xdist` algorithm to `worksteal`

---

ci/build_wheel.sh
ci/test_wheel.sh

This marks `cuxfilter` as a pure wheel, meaning that the CI artifacts are not specific to a Python version or CPU architecture. This change depends on https://github.com/rapidsai/gha-tools/pull/96, and makes CI workflows more robust by allowing the test matrix to be separated from the build matrix.

Treat cuxfilter CI artifacts as pure wheels

---

ci/build_docs.sh
ci/release/update-version.sh
docs/source/conf.py

* Read `cuxfilter.__version__` from docs build
* Update `ci/release/update-version.sh`
Issue: https://github.com/rapidsai/build-planning/issues/15

Remove hard-coding of RAPIDS version where possible

---

ci/build_docs.sh
ci/check_style.sh
ci/test_notebooks.sh
ci/test_python.sh

conda dropped support for the `--force` flag to `conda env create`. This changes that flag name to `--yes`.
See https://github.com/conda/conda/blob/main/CHANGELOG.md#2430-2024-03-12 and https://github.com/rapidsai/miniforge-cuda/pull/63 for more info.

Use `conda env create --yes` instead of `--force`

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-122_arch-x86_64.yaml
conda/recipes/cuxfilter/meta.yaml
dependencies.yaml

Replace libwebp with libwebp-base to resolve dependency conflict with the [cucim](https://github.com/rapidsai/cucim) package.

Fix libwebp dependency

---

python/.gitattributes

Contributes to https://github.com/rapidsai/build-planning/issues/31
Removes `.gitattributes` files.
These were added in #66 for use with `versioneer`. Per the `git` docs ([link](https://git-scm.com/docs/gitattributes#_export_subst)), setting the attribute `export-subst` on a file via a `.gitattributes` tell `git` to replace placeholders in the file with some `git` information.
This is no longer done in `_version.py` files in this project, and this project no longer uses `versioneer` (#497). `rapids-build-backend` handles storing git commit information in the published packages.
For more details, see https://github.com/rapidsai/build-planning/issues/31#issuecomment-2176853319

remove .gitattributes

---

python/cuxfilter/tests/assets/test_gpu_histogram.py

This just fixes a simple error that would appear when run with NumPy 2 based on the ruff check.
(This does not mean there are no other issues.)
xref: https://github.com/rapidsai/build-planning/issues/38

Run NumPy 2 ruff fixes (changing NaN to nan)

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml
.github/workflows/test.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
dependencies.yaml
docs/source/user_guide/installation.rst

This PR updates the latest CUDA build/test version 12.2.2 to 12.5.1.
Contributes to https://github.com/rapidsai/build-planning/issues/73

Build and test with CUDA 12.5.1

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml
.github/workflows/test.yaml

After updating everything to CUDA 12.5.1, use `shared-workflows@branch-24.08` again.
Contributes to https://github.com/rapidsai/build-planning/issues/73

Use workflow branch 24.08 again

---

README.md
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
dependencies.yaml
pyproject.toml
python/pyproject.toml

Contributes to https://github.com/rapidsai/build-planning/issues/88
Finishes the work of dropping Python 3.9 support.
This project stopped building / testing against Python 3.9 as of https://github.com/rapidsai/shared-workflows/pull/235.
This PR updates configuration and docs to reflect that.
Checked that there were no remaining uses like this:
```shell
git grep -E '3\.9'
git grep '39'
git grep 'py39'
```
And similar for variations on Python 3.8 (to catch things that were missed the last time this was done).

Drop Python 3.9 support

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml
.github/workflows/test.yaml
README.md
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
conda/recipes/cuxfilter/meta.yaml
dependencies.yaml
notebooks/README.md
python/pyproject.toml

Contributes to https://github.com/rapidsai/build-planning/issues/40
This PR adds support for Python 3.12.
This is part of ongoing work to add Python 3.12 support across RAPIDS.
It temporarily introduces a build/test matrix including Python 3.12, from https://github.com/rapidsai/shared-workflows/pull/213.
A follow-up PR will revert back to pointing at the `branch-24.10` branch of `shared-workflows` once all
RAPIDS repos have added Python 3.12 support.
Additional changes needed to add this support:
* dropping dependency on `pyppeteer` (https://github.com/rapidsai/cuxfilter/pull/625/files#r1750741079)
CI here is expected to fail until all of this project's upstream dependencies support Python 3.12.
This can be merged whenever all CI jobs are passing.

Add support for Python 3.12, drop pyppeteer dependency

---

.pre-commit-config.yaml
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
dependencies.yaml
python/cuxfilter/charts/core/non_aggregate/core_non_aggregate.py
python/cuxfilter/charts/core/non_aggregate/core_stacked_line.py
python/cuxfilter/dashboard.py

We need to update flake8 to fix a false-positive that appears with older flake8 versions on Python 3.12.

Update to flake8 7.1.1.

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml
.github/workflows/test.yaml

All RAPIDS libraries have been updated with Python 3.12 support, so Python 3.12 changes
have been merged into `branch-24.10` of `shared-workflows`: https://github.com/rapidsai/shared-workflows/pull/213
This updates GitHub Actions configs here to that branch.

Use CI workflow branch 'branch-24.10' again

---

README.md

Recommending `miniforge` for conda install in installation docs.

Recommend `miniforge` for conda installation

---

ci/test_python.sh
python/cuxfilter/tests/pytest.ini

In cudf & cuml we have observed a ~10% to ~20% respectively speed up of pytest suite execution by switching pytest traceback to `--native`:
```
currently:
102474 passed, 2117 skipped, 902 xfailed in 892.16s (0:14:52)
--tb=short:
102474 passed, 2117 skipped, 902 xfailed in 898.99s (0:14:58)
--tb=no:
102474 passed, 2117 skipped, 902 xfailed in 815.98s (0:13:35)
--tb=native:
102474 passed, 2117 skipped, 902 xfailed in 820.92s (0:13:40)
```
This PR makes a similar change to `cuxfilter` repo.
xref: https://github.com/rapidsai/cudf/pull/16851

Switch `traceback` to `native` in `pytest`

---

ci/build_docs.sh
ci/test_notebooks.sh
ci/test_python.sh

Contributes to https://github.com/rapidsai/build-planning/issues/106
Proposes specifying the RAPIDS version in `conda install` calls that install CI artifacts, to reduce the risk of CI jobs picking up artifacts from other releases.

make conda installs in CI stricter

---

.pre-commit-config.yaml
ci/build_python.sh
ci/build_wheel.sh

Contributes to https://github.com/rapidsai/build-planning/issues/108
Proposes removing `sccache` configuraiton in CI scripts ... this is a pure Python project, so it doesn't need that.
It also proposes updating the `rapids-dependency-file-generator` pre-commit hook to it's latest version (something I'm trying to roll out across RAPIDS as part of https://github.com/rapidsai/build-planning/issues/108), and reducing the verbosity of wheel-building scripts.

remove unnecessary sccache configuration, reduce verbosity of wheel-building scripts

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
conda/recipes/cuxfilter/meta.yaml
dependencies.yaml
python/pyproject.toml

Numba 0.61.0 just got released with couple of breaking changes, this pr is required to unblock the ci.
xref: https://github.com/rapidsai/cudf/pull/17777

Add upper bound to prevent usage of numba 0.61.0

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml
.github/workflows/test.yaml
.github/workflows/trigger-breaking-change-alert.yaml

This PR points the shared workflow branches back to the default 25.02 branches.
xref: https://github.com/rapidsai/build-planning/issues/139

Revert CUDA 12.8 shared workflow branch changes

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml
.github/workflows/test.yaml
.github/workflows/trigger-breaking-change-alert.yaml

This migrates amd64 CI jobs (PRs and nightlies) to use L4 GPUs from the NVKS cluster.
xref: https://github.com/rapidsai/build-infra/issues/184

Migrate to NVKS for amd64 CI runners

---

ci/build_wheel.sh
ci/test_external.sh
ci/test_wheel.sh

Uses a retry wrapper for `pip` commands to try to alleviate CI failures due to hash mismatches that result from network hiccups
xref rapidsai/build-planning#148
This will retry failures that show up in CI like:
```
Collecting nvidia-cublas-cu12 (from libraft-cu12==25.2.*,>=0.0.0a0)
Downloading https://pypi.nvidia.com/nvidia-cublas-cu12/nvidia_cublas_cu12-12.8.3.14-py3-none-manylinux_2_27_aarch64.whl (604.9 MB)
━━━━━━━━━━━━━━━━━━━━━                 350.2/604.9 MB 229.2 MB/s eta 0:00:02
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
nvidia-cublas-cu12 from …
```

Use `rapids-pip-retry` in CI jobs that might need retries

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml
.github/workflows/test.yaml
.github/workflows/trigger-breaking-change-alert.yaml

This completes the migration to NVKS runners now that all libraries have been tested and https://github.com/rapidsai/shared-workflows/pull/273 has been merged.
xref: https://github.com/rapidsai/build-infra/issues/184

Use shared-workflows branch-25.04

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-128_arch-x86_64.yaml
dependencies.yaml

Contributes to https://github.com/rapidsai/build-planning/issues/155
Fixes docs builds by temporarily putting a ceiling on `sphinx`.

require sphinx<8.2.0

---

ci/build_python.sh

This PR enables strict channel priority for building conda packages with `rattler-build`.
xref rapidsai/build-planning#84

refactor(rattler): enable strict channel priority for builds

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml
.github/workflows/test.yaml
.github/workflows/trigger-breaking-change-alert.yaml
README.md
conda/environments/all_cuda-118_arch-aarch64.yaml
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-128_arch-aarch64.yaml
conda/environments/all_cuda-128_arch-x86_64.yaml
conda/recipes/cuxfilter/recipe.yaml
dependencies.yaml
python/pyproject.toml

Contributes to https://github.com/rapidsai/build-planning/issues/120
This PR adds support for Python 3.13.
This is part of ongoing work to add Python 3.13 support across RAPIDS.
It temporarily introduces a build/test matrix including Python 3.13, from https://github.com/rapidsai/shared-workflows/pull/268.
A follow-up PR will revert back to pointing at the `branch-25.06` branch of `shared-workflows` once all
RAPIDS repos have added Python 3.13 support.
CI here is expected to fail until all of this project's upstream dependencies support Python 3.13.
This can be merged whenever all CI jobs are passing.

Add support for Python 3.13

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml
.github/workflows/test.yaml
ci/build_wheel.sh
ci/test_wheel.sh

Proposes a batch of small, mostly-unrelated changes to building and packaging.
These are all part of RAPIDS-wide efforts to make it easier to reproduce CI locally and to use artifacts from one project's CI in another project's CI.
Contributes to https://github.com/rapidsai/build-planning/issues/178
* prevents triggering expensive CI jobs based on PRs modifying `ci/release/update-version.sh`
Contributes to https://github.com/rapidsai/shared-workflows/issues/356
* explicitly provides an input for `script` to workflows using it, instead of relying on a default value coming from the workflow file
Contributes to https://github.com/rapidsai/shared-workflows/issues/337
* switches from input `run_script` to `script` in uses of the `custom-job` workflow
Contributes to …

use 'rapids-init-pip' in wheel CI, other CI changes

---

.pre-commit-config.yaml
ci/build_python.sh
ci/build_wheel.sh

Contributes to https://github.com/rapidsai/build-planning/issues/181
* removes all uploads of conda packages and wheels to `downloads.rapids.ai`
Also updates a few RAPIDS `pre-commit` hook versions, while were a bit out of date.
Looked for uses of the relevant `gha-tools` tools, as well as documentation about `downloads.rapids.ai`, being on the NVIDIA VPN, using S3, etc. like this:
```shell
git grep -i -E 's3|upload|downloads\.rapids|vpn'
```
See "How I tested this" on https://github.com/rapidsai/shared-workflows/pull/364

stop uploading packages to downloads.rapids.ai

---

dependencies.yaml

Cleaned out some remaining `cuspatial` references recently with PR: https://github.com/rapidsai/cuxfilter/pull/700
Found we missed one. Removing that here

Drop one more `cuspatial` reference

---

conda/environments/all_cuda-128_arch-aarch64.yaml
conda/environments/all_cuda-128_arch-x86_64.yaml
dependencies.yaml
python/pyproject.toml

The nightly builds on cuxfilter started failing 5 days ago. This lines up with when Holoviews 1.21.0 was released. Pin to Holoviews pre-1.21.0 as a temporary measure to clear up CI.

Pin Holoviews pre-1.21.0

---

README.md
conda/environments/all_cuda-129_arch-aarch64.yaml
conda/environments/all_cuda-129_arch-x86_64.yaml
dependencies.yaml
docs/source/user_guide/installation.rst

Addressing issues:
* https://github.com/rapidsai/build-planning/issues/195
* https://github.com/rapidsai/build-planning/issues/173
Use CUDA 12.9 throughout different build and test environments.

Use CUDA 12.9 in Conda, Devcontainers, Spark, GHA, etc.

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml
.github/workflows/test.yaml
.github/workflows/trigger-breaking-change-alert.yaml

Contributes to https://github.com/rapidsai/build-planning/issues/208
Now that https://github.com/rapidsai/shared-workflows/pull/413 is merged, this converts all GitHub Actions references from `@cuda13.0` back to `branch-25.10`.
This is safe to admin-merge because the change is a no-op... configs on those 2 branches are identical.

Use branch-25.10 again

---

conda/environments/all_cuda-129_arch-aarch64.yaml
conda/environments/all_cuda-129_arch-x86_64.yaml
conda/environments/all_cuda-130_arch-aarch64.yaml
conda/environments/all_cuda-130_arch-x86_64.yaml
conda/recipes/cuxfilter/recipe.yaml
dependencies.yaml
python/pyproject.toml

Contributes to https://github.com/rapidsai/build-planning/issues/214, updating pins to match the rest of RAPIDS:
* numba: `>=0.60.0,<0.62.0a0`
This tighter `numba` pin is already anyway constraining this project because `cuxfilter` depend on `cudf`, so this change should have 0 effect on this project's current state.
Making the pin explicit makes it a bit easier to do all-of-RAPIDS updates in the future if needed.

update dependencies: numba (>= 0.60.0)
