Dockerfile

updated the minimum required pandas, numpy and pyarrow version for cudf 0.5.0

updated Dockerfile to support cudf=0.5.0

---

python/cuXfilter/charts/bokeh/__init__.py
python/cuXfilter/charts/bokeh/bokeh.py
python/cuXfilter/charts/bokeh/plots.py
python/cuXfilter/charts/core/aggregate/core_aggregate_choropleth.py
python/cuXfilter/charts/panel_widgets/panel_widgets.py

- added tile_provider option for choropleth maps,
- fixed layout issues for widgets

added tile_provider option for choropleth maps,

---

python/cudf_dev_cuda10.0.yml

Updated dependencies to rapids 0.10

updated to rapids=0.10

---

python/cuXfilter/assets/numba_kernels/gpu_datatile.py
python/cuXfilter/charts/core/aggregate/core_aggregate.py
python/cuXfilter/charts/core/aggregate/core_aggregate_bar.py
python/cuXfilter/charts/core/aggregate/core_aggregate_choropleth.py
python/cuXfilter/charts/core/aggregate/core_aggregate_line.py
python/cuXfilter/charts/core/core_chart.py
python/cuXfilter/dataframe.py

Fixed data_tile calculation accuracy issue around range edges for filters

fixed calculation accuracies for range edges and filter_by_indices

---

python/cuXfilter/charts/bokeh/bokeh.py
python/cuXfilter/charts/bokeh/plots.py
python/cuXfilter/charts/cudatashader/cudatashader.py
python/cuXfilter/charts/cudatashader/plots.py

- Added title attribute to charts, and minor bug fixes
- Updated docs

added title attribute to charts, and minor bug fixes

---

python/cuXfilter/charts/core/aggregate/core_aggregate_bar.py
python/cuXfilter/charts/core/aggregate/core_aggregate_choropleth.py
python/cuXfilter/charts/core/aggregate/core_aggregate_line.py

minor bug fix related to stride calculations for datatiles

---

python/Makefile

When installing following the [conda environment instructions](https://github.com/rapidsai/cuxfilter#2-if-installing-in-a-conda-environment) from the README the environment file referenced in the `Makefile` appears not to exist. 
This PR updates the path to what I think might be the correct environment file.

Fix path to conda environment

---

conda/environments/cuxfilter_dev_cuda10.0.yml
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda9.2.yml
conda/recipes/cuxfilter/meta.yaml
python/Makefile
python/cuxfilter/assets/geojson_mapper.py

- Updating pyproj version based on the discussion in #71
- Dependency file names to lowercase

Dependency resolution

---

python/cuxfilter/charts/__init__.py
python/cuxfilter/dashboard.py
python/cuxfilter/dataframe.py
python/cuxfilter/tests/test_dashboard.py
python/cuxfilter/tests/test_datatile.py
python/notebooks/NYC_taxi_example.ipynb

import cuxfilter related fixes for cpuci smoke tests during conda build

---

CHANGELOG.md
README.md
ci/gpu/build.sh
python/cuxfilter/assets/screengrab.py
python/cuxfilter/dashboard.py

Docker issues

---

CHANGELOG.md
python/cuxfilter/__init__.py
python/cuxfilter/assets/__init__.py
python/cuxfilter/assets/notebook_assets.py
python/cuxfilter/charts/__init__.py
python/cuxfilter/charts/core/core_chart.py
python/cuxfilter/charts/core/core_view_dataframe.py
python/cuxfilter/charts/core/core_widget.py
python/cuxfilter/charts/panel_widgets/plots.py
python/cuxfilter/dashboard.py
python/cuxfilter/tests/charts/core/test_core_view_dataframe.py
python/cuxfilter/tests/charts/core/test_core_widget.py
python/notebooks/Mortgage_example.ipynb

- Faster import time
- Segregated in-notebook asset loading to save import costs, using cuxfilter.load_notebook_assets() useful only for viewing individual charts within notebook.
Example:
Only required in notebooks/jupyterlab
```python
import cuxfilter
cux_df = cuxfilter.DataFrame.from_arrow(DATA_DIR + '/146M_predictions_v2.arrow')
chart = cuxfilter.charts.bokeh.bar('delinquency_12_prediction',data_points=50)
d = cux_df.dashboard([chart])
cuxfilter.load_notebook_assets()
chart0
```
Output
```bash 
cuxfilter notebook assets successfully loaded.
```
- Updated tests
- Updated notebooks

Import and warning improvements

---

ci/release/update-version.sh
docs/source/conf.py

[REVIEW] Add update-version [skip-ci]

---

CHANGELOG.md
python/cuxfilter/assets/numba_kernels/gpu_histogram.py
python/cuxfilter/charts/deckgl/bindings/polygon.py
python/cuxfilter/charts/deckgl/bindings/typescript_files/PolygonDeckGL.ts
python/cuxfilter/charts/deckgl/bindings/typescript_files/PolygonDeckGLView.ts
python/cuxfilter/charts/deckgl/bindings/typescript_impl.py
python/cuxfilter/charts/deckgl/plots.py
python/cuxfilter/datatile.py

- fixed naming issue for geo column for choropleth3d charts, which did not allow all-small-caps names

fixed issues #102

---

ci/release/update-version.sh
conda/environments/cuxfilter_dev_cuda10.0.yml
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda9.2.yml

fixes #107

---

CHANGELOG.md
ci/gpu/build.sh
conda/environments/cuxfilter_dev_cuda10.0.yml
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda9.2.yml
conda/recipes/cuxfilter/meta.yaml

update bokeh dependency to use 1.* instead of >1, as 2.0 failis

---

ci/cpu/prebuild.sh
ci/gpu/build.sh

Auto-merge triggered by push to `branch-0.13` that creates a PR to keep `branch-0.14` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.13 to branch-0.14 [skip ci]

---

CHANGELOG.md
python/cuxfilter/charts/core/aggregate/core_aggregate_choropleth.py
python/cuxfilter/charts/deckgl/plots.py
python/cuxfilter/datatile.py

- fixes #125
- fixed logic for calculating datatiles for 2d and 3d choropleth charts

Bug fix choropleth

---

CHANGELOG.md
python/cuxfilter/charts/core/aggregate/core_aggregate_bar.py
python/cuxfilter/charts/core/aggregate/core_aggregate_line.py
python/cuxfilter/charts/core/non_aggregate/core_line.py
python/cuxfilter/charts/core/non_aggregate/core_non_aggregate.py
python/cuxfilter/charts/core/non_aggregate/core_stacked_line.py
python/cuxfilter/charts/panel_widgets/plots.py
python/cuxfilter/dashboard.py

- optimizations to grouby query, using boolean masks
- adding conditions for enforcing limit on datapoint binedges

Query optimizations and bug fixes

---

CHANGELOG.md
notebooks/NYC_taxi_example.ipynb
python/cuxfilter/charts/core/aggregate/core_aggregate_bar.py
python/cuxfilter/sampledata/download_datasets.py
python/cuxfilter/tests/test_dashboard.py

adding conditions for enforcing limit on datapoint binedges

adding conditions for enforcing limit on datapoint binedges

---

CHANGELOG.md
python/cuxfilter/charts/datashader/plots.py
python/cuxfilter/dashboard.py

bug fix where generate chart is called twice which led to box-select tool filter not working on the following charts:
1. scatter
2. scatter-geo
3. datashader line
4. datashader stacked lines
5. heatmap

Filter fix for non aggregate charts

---

CHANGELOG.md
python/cuxfilter/charts/core/aggregate/core_aggregate.py
python/cuxfilter/charts/datashader/plots.py
python/cuxfilter/dashboard.py
python/cuxfilter/tests/charts/core/test_core_aggregate.py

Aggregate charts were facing an issue where the datatiles computed weren't accurate for range selections(were missing zero value indexes)
- fixed updating chart data as per accurate indices
- fixed sending incorrect cuDF to aggregate data_tile compute
- updated tests

Aggregate filter accuracy fix

---

CHANGELOG.md
ci/gpu/build.sh
conda/environments/cuxfilter_dev_cuda10.0.yml
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda9.2.yml
conda/recipes/cuxfilter/meta.yaml
python/cuxfilter/charts/core/aggregate/core_aggregate.py

- added nodejs dependency
- minor bug fixes

Minor bug and dependency fix

---

CHANGELOG.md
python/cuxfilter/charts/core/non_aggregate/core_non_aggregate.py

Non-aggregate chart type queries were current state dependent. This PR converts non-aggregate query to being stateless, a step closer to multi-user dashboard experience.

making non-aggregate query stateless

---

CHANGELOG.md
python/cuxfilter/layouts/layouts.py
python/cuxfilter/tests/layouts/test_layouts.py

- Last layout refactor PR actually had a couple of bugs, this PR fixes those

Layout bug fixes [Review]

---

CHANGELOG.md
python/cuxfilter/dashboard.py
python/cuxfilter/layouts/__init__.py
python/cuxfilter/layouts/layout_templates.py
python/cuxfilter/layouts/layouts.py
python/cuxfilter/tests/layouts/test_layout_templates.py

@AjayThorve Here is some more light refactoring/cleanup. I think most of the commits are self-contained / self-explanatory but it's also a bit of a hodge-podge, since its just things I noticed while reading to learn the codebase, so a few comments:
* ***De-duplication*** Much of the PR is just refactoring things that are duplicated to not be duplicated.
* ***Optional values*** I changed a couple of places that used "" as an missing optional. None is more idiomatic and plays better with MyPy e.g. `Optional[str]`, or alternatively just using an actual real default value. 
* ***Unnecessary properties*** My thoughts on these have definitely evolved. :) I also used to favor them but after spending some time with some Python core devs at MS, I have come around to the notion that properties like …

Dashboard and templates cleanup and tests

---

CONTRIBUTING.md
ci/checks/changelog.sh

Auto-merge triggered by push to `branch-0.15` that creates a PR to keep `branch-0.16` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.15 to branch-0.16 [skip ci]

---

CHANGELOG.md
README.md
ci/gpu/build.sh
conda/environments/cuxfilter_dev_cuda10.0.yml
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/recipes/cuxfilter/meta.yaml
docs/source/charts/bokeh_charts.rst
docs/source/charts/custom_charts.rst
docs/source/charts/datashader_charts.rst
docs/source/charts/deckgl_charts.rst
docs/source/charts/panel_widgets.rst
docs/source/conf.py
docs/source/deployment.rst
docs/source/index.rst
notebooks/Mortgage_example.ipynb
notebooks/NYC_taxi_example.ipynb
notebooks/auto_accidents_example.ipynb
notebooks/graphs.ipynb
python/cuxfilter/charts/datashader/custom_extensions/graph_assets.py

This PR is dependent on https://github.com/rapidsai/ops/issues/1097 and https://github.com/rapidsai/integration/pull/112. 
- Datashader minimum version pin ensures it works with cuDF 0.14 and above. 
- Minor changes to docs - fixing chart rendering issues
cc @exactlyallan

Datashader version pin and doc updates - release blocker

---

CHANGELOG.md
notebooks/graphs.ipynb
python/cuxfilter/charts/datashader/custom_extensions/graph_assets.py

fixes ci failure issue in #183

pre-release patch

---

CHANGELOG.md
conda/environments/cuxfilter_dev_cuda10.0.yml
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
docs/source/conf.py

reverting the changes caused by problematic merge commit (https://github.com/rapidsai/cuxfilter/commit/089c6115009b2f184ebd5ad53c95342aa4386917)

fix cudf version

---

CHANGELOG.md
README.md
ci/gpu/build.sh
conda/environments/cuxfilter_dev_cuda10.0.yml
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/recipes/cuxfilter/meta.yaml
docs/source/charts/bokeh_charts.rst
docs/source/charts/custom_charts.rst
docs/source/charts/datashader_charts.rst
docs/source/charts/deckgl_charts.rst
docs/source/charts/panel_widgets.rst
docs/source/conf.py
docs/source/deployment.rst
docs/source/index.rst
notebooks/Mortgage_example.ipynb
notebooks/NYC_taxi_example.ipynb
notebooks/auto_accidents_example.ipynb
notebooks/graphs.ipynb
python/cuxfilter/charts/datashader/custom_extensions/graph_assets.py

Branch 0.16 merge 0.15

---

CHANGELOG.md
python/cuxfilter/charts/core/__init__.py
python/cuxfilter/charts/core/core_view_dataframe.py
python/cuxfilter/charts/core/non_aggregate/core_graph.py
python/cuxfilter/charts/core/non_aggregate/core_non_aggregate.py
python/cuxfilter/charts/core/non_aggregate/core_stacked_line.py
python/cuxfilter/charts/datashader/custom_extensions/graph_assets.py
python/cuxfilter/charts/datashader/plots.py
python/cuxfilter/tests/charts/core/test_core_graph.py
python/cuxfilter/tests/charts/core/test_core_view_dataframe.py

Bug fixes
- fixes issues with non_aggregate charts having permanent inplace querying and query_by_indices
Feature Additions:
- Added drop_duplicates for view_dataframe chart type
- Optimized graph querying logic

Minor Fixes and drop_duplicates attr for view_dataframe()

---

CHANGELOG.md
python/cuxfilter/dashboard.py

- Added `service_proxy` parameter to `cuxfilter.dashboard.show` and `cuxfilter.dashboard.app`, setting it to 'jupyterhub', will make sure cuxfilter dashboard works in a jupyterhub/mybinder environment.
- inspired by the bokeh implementation - http://docs.bokeh.org/en/latest/docs/user_guide/jupyter.html#jupyterhub

updated show and app methods for jupyterhub

---

CHANGELOG.md
python/cuxfilter/dashboard.py

- this pr addresses a minor issue with jupyterhub support PR - fixes issue with static http scheme applied for dashboard url, now picking scheme from base_url

Jupyterhub support - patch

---

CHANGELOG.md
ci/local/README.md
python/cuxfilter/dashboard.py

Auto-merge triggered by push to `branch-0.16` that creates a PR to keep `branch-0.17` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.16 to branch-0.17 [skip ci]

---

CHANGELOG.md
ci/docs/build.sh

This PR fixes link to docs _build directory

docs build fix

---

CHANGELOG.md
python/cuxfilter/assets/numba_kernels/gpu_datatile.py
python/cuxfilter/assets/numba_kernels/gpu_histogram.py
python/cuxfilter/charts/datashader/custom_extensions/graph_assets.py
python/cuxfilter/tests/assets/test_gpu_datatile.py

remove legacy parameter `method="hash"`
remove `to_gpu_matrix` and `add_column` - ref [cudf PR](https://github.com/rapidsai/cudf/pull/6442)

[REVIEW] remove deprecated cudf methods

---

CHANGELOG.md
ci/gpu/build.sh
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml

[hotfix] pin panel <=0.9.7, and close a few open-ended pins

---

CHANGELOG.md
python/cuxfilter/dashboard.py

Minor changes - added keyword arguments for get_server. `address` parameter was getting assigned as one of the positional arguments, when it should have been a default value, which was leading to a `gaierror` bug when running `cux_df.dashboard()` function.

Patch fix for panel >0.10.0

---

CHANGELOG.md
ci/gpu/build.sh
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml
python/cuxfilter/dashboard.py

- minor fixes and closing open-ended dependencies for bokeh, panel, pyproj & geopandas

Close open ended dependencies

---

CHANGELOG.md
ci/gpu/build.sh
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml
python/cuxfilter/dashboard.py

Branch 0.18 merge 0.17 - fix auto merge conflicts

---

CHANGELOG.md
python/cuxfilter/charts/core/aggregate/core_number_chart.py
python/cuxfilter/charts/core/non_aggregate/core_graph.py
python/cuxfilter/charts/core/non_aggregate/core_non_aggregate.py
python/cuxfilter/charts/core/non_aggregate/core_stacked_line.py
python/cuxfilter/dashboard.py

This PR fixes the issue which prevented lasso select queries to preserve current filtered state of the dashboard.

fix state preserving issue for lasso-select callbacks

---

CHANGELOG.md

This PR fixes the merge conflicts in #233.

Fix merge conflicts in #233 [skip-ci]

---

python/cuxfilter/layouts/assets/react.html

Auto-merge triggered by push to `branch-0.18` that creates a PR to keep `branch-0.19` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.18 to branch-0.19 [skip ci]

---

ci/gpu/build.sh

Use `gpuci_conda_retry` in https://github.com/rapidsai/cuxfilter/blob/branch-0.20/ci/gpu/build.sh

FIX Use gpuci_conda_retry in ci/gpu/build.sh

---

conda/recipes/cuxfilter/meta.yaml

Follow up from #270 to update the `meta.yaml`

Update pyproj version in meta.yaml

---

CHANGELOG.md
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml

This PR fixes the conflicts in #269.

Fix forward merge conflicts [skip ci]

---

python/cuxfilter/charts/deckgl/plots.py
python/cuxfilter/themes/dark.py
python/cuxfilter/themes/light.py
python/cuxfilter/themes/rapids.py

This PR adds base map styles for choropleth pydeck charts for cases when no mapbox token is provided. Closes #266

[FEA] add map_style for no-token cases

---

python/cuxfilter/layouts/assets/react.css

replace overflow-y:scroll -> auto

---

conda/recipes/cuxfilter/meta.yaml

Pass compiler environment variables to conda python build

Pass compiler environment variables to conda python build

---

CHANGELOG.md
conda/recipes/cuxfilter/meta.yaml

This PR fixes the forward merging conflicts in #288.

Fix merge conflicts [skip ci]

---

ci/cpu/build.sh
ci/docs/build.sh
ci/gpu/build.sh
ci/gpu/test-notebooks.sh
ci/local/build.sh
ci/utils/nbtest.sh

Forward-merge triggered by push to `branch-21.06` that creates a PR to keep `branch-21.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.06 to branch-21.08 [skip ci]

---

conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml

update pyproj version

---

python/cuxfilter/charts/core/aggregate/core_aggregate.py
python/cuxfilter/charts/core/core_widget.py
python/cuxfilter/dashboard.py
python/cuxfilter/layouts/custom_react_template.py
python/cuxfilter/themes/assets/rapids.css
python/cuxfilter/themes/rapids.py

Forward-merge triggered by push to `branch-21.08` that creates a PR to keep `branch-21.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.08 to branch-21.10 [skip ci]

---

README.md
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml
python/cuxfilter/assets/screengrab.py

Remove pyppeteer dependency to fix unstable containers, stemming from [this issue](https://github.com/pyppeteer/pyppeteer/issues/275#issuecomment-882838194)

remove pyppeteer dependency and add instructions to the Readme

---

README.md
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml
python/cuxfilter/assets/screengrab.py

Forward-merge `21.06` changes into `21.08`.

Forward merge `21.06` into `21.08`

---

python/cuxfilter/assets/screengrab.py

Forward merge 21.06 into 21.08

---

README.md
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml
python/cuxfilter/assets/screengrab.py

This PR merges the following changes into `main`:
- https://github.com/rapidsai/cuxfilter/pull/307

[RELEASE] 21.06.01 Hotfix Release

---

CHANGELOG.md
README.md
ci/docs/build.sh
ci/gpu/build.sh
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml
docs/source/conf.py
python/cuxfilter/charts/core/aggregate/core_aggregate.py
python/cuxfilter/charts/core/core_widget.py
python/cuxfilter/charts/datashader/custom_extensions/graph_inspect_widget.py
python/cuxfilter/dashboard.py
python/cuxfilter/layouts/custom_react_template.py
python/cuxfilter/themes/assets/rapids.css
python/cuxfilter/themes/rapids.py

Only critical/hotfix level issues should be merged into `branch-21.08` until release (merging of this PR).
- Update documentation
- Allow testing for the new release
- Enable a means to merge `branch-21.08` into `main` for the release

[RELEASE] cuxfilter v21.08

---

CHANGELOG.md

Branch 21.10 merge 21.08

---

conda/recipes/cuxfilter/meta.yaml

Temporary workaround to skip imports tests on arm64

Skip imports tests on arm64

---

README.md
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml
python/cuxfilter/assets/screengrab.py

reverts the removal of pyppeteer since CI issues seem to be resolved.

revert pyppeteer dependency changes

---

ci/gpu/build.sh
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml
python/cuxfilter/dashboard.py

- Resolves reset chart issue
- Adds support for bokeh 2.4.0 and panel 0.12.4

fix chart names being saved as incorrect keys prior to initialization

---

ci/gpu/build.sh
conda/environments/cuxfilter_dev_cuda10.1.yml
conda/environments/cuxfilter_dev_cuda10.2.yml
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/recipes/cuxfilter/meta.yaml
python/cuxfilter/dashboard.py

Forward-merge triggered by push to `branch-21.10` that creates a PR to keep `branch-21.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.10 to branch-21.12 [skip gpuci]

---

python/cuxfilter/dashboard.py
python/cuxfilter/dataframe.py

update docstrings examples to fix #328

---

python/cuxfilter/dashboard.py
python/cuxfilter/dataframe.py

Forward-merge triggered by push to `branch-21.12` that creates a PR to keep `branch-22.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.12 to branch-22.02 [skip gpuci]

---

conda/recipes/cuxfilter/meta.yaml

Fix imports tests syntax

---

ci/gpu/build.sh
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/environments/cuxfilter_dev_cuda11.2.yml
conda/environments/cuxfilter_dev_cuda11.4.yml
conda/environments/cuxfilter_dev_cuda11.5.yml
conda/recipes/cuxfilter/meta.yaml

Forward-merge triggered by push to `branch-22.04` that creates a PR to keep `branch-22.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.04 to branch-22.06 [skip gpuci]

---

conda/environments/cuxfilter_dev_cuda11.0.yml
conda/environments/cuxfilter_dev_cuda11.2.yml
conda/environments/cuxfilter_dev_cuda11.4.yml
conda/environments/cuxfilter_dev_cuda11.5.yml
conda/recipes/cuxfilter/meta.yaml

update datashader version pin to `>0.13` to accomdate custom version `0.13.1a` which has update cudf-api fixes. (`<0.14` as next official release of datashader will also have those fixes in)

update datashader version pins

---

CHANGELOG.md
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/environments/cuxfilter_dev_cuda11.2.yml
conda/environments/cuxfilter_dev_cuda11.4.yml
conda/environments/cuxfilter_dev_cuda11.5.yml
conda/recipes/cuxfilter/meta.yaml

Fixes conflicts in https://github.com/rapidsai/cuxfilter/pull/365

Forward-merge branch-22.04 to branch-22.06

---

conda/recipes/cuxfilter/meta.yaml

Simplify recipes using `{{ target_platform }}` for `sysroot` package

Simplify conda recipe

---

conda/environments/cuxfilter_dev_cuda11.0.yml
conda/environments/cuxfilter_dev_cuda11.2.yml
conda/environments/cuxfilter_dev_cuda11.4.yml
conda/environments/cuxfilter_dev_cuda11.5.yml
conda/recipes/cuxfilter/meta.yaml

Allows cuxfilter to be installed with CuPy 11.
xref: https://github.com/rapidsai/integration/pull/508

Allow CuPy 11

---

CHANGELOG.md
conda/environments/cuxfilter_dev_cuda11.0.yml
conda/environments/cuxfilter_dev_cuda11.2.yml
conda/environments/cuxfilter_dev_cuda11.4.yml
conda/environments/cuxfilter_dev_cuda11.5.yml
conda/recipes/cuxfilter/meta.yaml

Forward-merge triggered by push to `branch-22.08` that creates a PR to keep `branch-22.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.08 to branch-22.10 [skip gpuci]

---

conda/environments/cuxfilter_dev_cuda11.0.yml
conda/environments/cuxfilter_dev_cuda11.2.yml
conda/environments/cuxfilter_dev_cuda11.4.yml
conda/environments/cuxfilter_dev_cuda11.5.yml
conda/recipes/cuxfilter/meta.yaml

Reverts rapidsai/cuxfilter#383

Revert "Allow CuPy 11"

---

docs/source/conf.py

This PR switches docs to use the custom common `js` & `css` code merged here: https://github.com/rapidsai/docs/pull/286

[REVIEW] Use common custom `js` & `css` code

---

notebooks/Additional Visualizations Catalogue/RAPIDS Viz Catalog.ipynb
notebooks/Additional Visualizations Catalogue/README.md

Added Viz Catalog notebook with Readme

---

conda/environments/cuxfilter_dev_cuda11.0.yml
conda/environments/cuxfilter_dev_cuda11.2.yml
conda/environments/cuxfilter_dev_cuda11.4.yml
conda/environments/cuxfilter_dev_cuda11.5.yml
conda/recipes/cuxfilter/meta.yaml

This PR updates the `panel` version to the latest in order to resolve some conflicts with `setuptools`.
xref: https://github.com/rapidsai/integration/pull/575.

Update `panel` version

---

ci/build_docs.sh

fixes issue in #[436](https://github.com/rapidsai/cuxfilter/pull/436#discussion_r1081603157)
cc @ajschmidt8

fix path for dir to uploaded

---

build.sh

Forward-merge triggered by push to `branch-23.02` that creates a PR to keep `branch-23.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-23.02 to branch-23.04

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/recipes/cuxfilter/meta.yaml
dependencies.yaml
docs/source/conf.py
python/cuxfilter/charts/datashader/custom_extensions/holoviews_datashader.py

Since datashader merged the changes fixing cupy array compatiblity with `datashader.transfer_functions.dynspread` and `spread`, it's safe to use the latest stable datashader version, and the inbuilt function, instead of a custom `dynspread` function which was handling `cupy` array edge case

Update datashader version

---

README.md
docs/source/10_minutes_to_cuxfilter.ipynb
docs/source/installation.rst
notebooks/Mortgage_example.ipynb
notebooks/NYC_taxi_example.ipynb
notebooks/auto_accidents_example.ipynb
notebooks/cuxfilter_with_dask_cudf/Mortgage_example.ipynb
notebooks/cuxfilter_with_dask_cudf/NYC_taxi_example.ipynb
notebooks/cuxfilter_with_dask_cudf/auto_accidents_example.ipynb
python/cuxfilter/sampledata/download_datasets.py

Update datasets download URL to reduce latency and costs

Update datasets download URL

---

.github/workflows/test-external.yaml

fix input paramter to workflow

---

python/cuxfilter/sampledata/download_datasets.py

Forward-merge triggered by push to `branch-23.04` that creates a PR to keep `branch-23.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-23.04 to branch-23.06

---

.github/workflows/test-external.yaml
ci/release/update-version.sh
ci/test_external.sh

Based on the discussion in #452, adding a weekly schedule to run the external dependency testing workflow.
cc @exactlyallan @ajschmidt8

GHA - external dependency testing workflow: add a schedule to run once every week

---

.github/workflows/test-external.yaml
ci/release/update-version.sh
ci/test_external.sh
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/recipes/cuxfilter/meta.yaml
dependencies.yaml
python/cuxfilter/tests/assets/test_gpu_histogram.py
python/cuxfilter/tests/charts/core/test_core_graph.py
python/cuxfilter/tests/charts/utils.py

Forward-merge triggered by push to `branch-23.06` that creates a PR to keep `branch-23.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-23.06 to branch-23.08

---

.github/workflows/test-external.yaml

Fix scheduled GHA workflow issue

---

ci/release/update-version.sh
ci/test_external.sh

The workflow was picking up incorrect version(stable) of cudf from rapidsai-nightly channel (since patch 23.06.1 was released), causing the install and hence the tests to fail.
This PR updates the workflow to install cudf from the rapidsai channel

Fix GHA: external dependencies tests

---

.github/workflows/test-external.yaml

This is a follow-up PR to #503, which reverts changes to the branch of shared-action-workflows used for CUDA 12 testing, for the pending workflows.

Followup: Revert CUDA 12.0 CI workflows to branch-23.08

---

.github/workflows/test-external.yaml
ci/test_external.sh
ci/utils/external_dependencies.yaml

Resolves #509. Adds more libraries to test installs against `cuxfilter`, along with testing pyviz+RAPIDS cuDF, dask-cudf capabilities.

Improve external tests

---

README.md
ci/test_external.sh
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-120_arch-x86_64.yaml
dependencies.yaml
docs/source/api_reference/dataframe.rst
python/cuxfilter/dashboard.py

This PR fixes a version issue in ci/test_external.sh which was caused by an incorrect cuda-version. Also updated README.md install instructions.
fixes #533, #532
cc @exactlyallan

fix external workflow

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test-external.yaml

PR updates `rapidsai/ci` references to `rapidsai/ci-conda`

Update image names

---

ci/test_external.sh
ci/utils/external_dependencies.yaml

Fix external tests workflow having a cupy version issue.
cc @exactlyallan

fix workflow

---

docs/source/user_guide/charts/widgets.rst

This PR fixes the ci docs build issue, because of inconsitent datestring in one of the docstrings. where the support for it was updated in the recent cudf.pandas version.

Consistent datestring format to fix parsing error

---

ci/release/update-version.sh

This PR fixes the `ci/release/update-version.sh`  script, that updates the missing release version updates in some files.
cc @raydouglass

Fix Release Script: Update all references to release versions

---

.github/workflows/test-external.yaml
ci/test_external.sh
ci/utils/external_dependencies.yaml

This PR aims to fix the failing external tests: https://github.com/rapidsai/cuxfilter/actions/runs/7215132031, last PR #555 did not seem to fix it. 
Removing tensorflow due to #560.
cc @ajschmidt8

External workflow - remove tensorflow

---

python/cuxfilter/charts/datashader/custom_extensions/holoviews_datashader.py
python/cuxfilter/charts/datashader/datashader.py
python/cuxfilter/charts/datashader/plots.py

This PR adds the option to enable/disable the axes (x and y) for scatter, heatmap and graph charts.
The default is False for scatter and graph, while it's True for heatmaps.
1. Graph:
2. Scatter:
3. Heatmap
implements #573

add option to enable/disable axes

---

python/cuxfilter/charts/datashader/custom_extensions/holoviews_datashader.py
python/cuxfilter/charts/datashader/datashader.py
python/cuxfilter/charts/datashader/plots.py

Forward-merge triggered by push to `branch-24.04` that creates a PR to keep `branch-24.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-24.04 to branch-24.06

---

python/pyproject.toml

Part of https://github.com/rapidsai/build-planning/issues/26
Luckily it doesn't appear the current test suite has any :)

Enable FutureWarnings/DeprecationWarnings as errors

---

README.md
conda/environments/all_cuda-128_arch-x86_64.yaml
dependencies.yaml
docs/source/user_guide/installation.rst

Manual forward merge from 25.02 to 25.04. This PR should not be squashed.

Forward-merge branch-25.02 into branch-25.04

---

conda/recipes/cuxfilter/recipe.yaml
dependencies.yaml

Fixes forward merger xref #686

Forward-merge branch-25.06 into branch-25.08
